
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'







interface PoolConstructorInput {
  id: ID;
  asset0: String;
  asset1: String;
  isStable: Boolean;
  lpToken: String;
  lpTokenSupply: BigInt;
  lpTokenSupplyDecimal: Float;
  reserve0: BigInt;
  reserve1: BigInt;
  reserve0Decimal: Float;
  reserve1Decimal: Float;
  volumeAsset0: BigInt;
  volumeAsset1: BigInt;
  volumeAsset0Decimal: Float;
  volumeAsset1Decimal: Float;
  mostRecentSnapshot: Int;
}
@Entity("Pool")
export class Pool extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	asset0: String

	@Required
	@Column("String")
	asset1: String

	@Required
	@Column("Boolean")
	isStable: Boolean

	@Required
	@Column("String")
	lpToken: String

	@Required
	@Column("BigInt")
	lpTokenSupply: BigInt

	@Required
	@Column("Float")
	lpTokenSupplyDecimal: Float

	@Required
	@Column("BigInt")
	reserve0: BigInt

	@Required
	@Column("BigInt")
	reserve1: BigInt

	@Required
	@Column("Float")
	reserve0Decimal: Float

	@Required
	@Column("Float")
	reserve1Decimal: Float

	@Required
	@Column("BigInt")
	volumeAsset0: BigInt

	@Required
	@Column("BigInt")
	volumeAsset1: BigInt

	@Required
	@Column("Float")
	volumeAsset0Decimal: Float

	@Required
	@Column("Float")
	volumeAsset1Decimal: Float

	@Required
	@Column("Int")
	mostRecentSnapshot: Int
  constructor(data: PoolConstructorInput) {super()}

}


interface PoolSnapshotConstructorInput {
  id: ID;
  poolID?: ID;
  timestamp: Int;
  lpTokenSupply: BigInt;
  lpTokenSupplyDecimal: Float;
  transactions: Int;
  reserve0: BigInt;
  reserve1: BigInt;
  reserve0Decimal: Float;
  reserve1Decimal: Float;
  volumeAsset0: BigInt;
  volumeAsset1: BigInt;
  volumeAsset0Decimal: Float;
  volumeAsset1Decimal: Float;
}
@Entity("PoolSnapshot")
export class PoolSnapshot extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@One("Pool")
	_pool: Promise<Pool>

	poolID: ID

	@Required
	@Column("Int")
	timestamp: Int

	@Required
	@Column("BigInt")
	lpTokenSupply: BigInt

	@Required
	@Column("Float")
	lpTokenSupplyDecimal: Float

	@Required
	@Column("Int")
	transactions: Int

	@Required
	@Column("BigInt")
	reserve0: BigInt

	@Required
	@Column("BigInt")
	reserve1: BigInt

	@Required
	@Column("Float")
	reserve0Decimal: Float

	@Required
	@Column("Float")
	reserve1Decimal: Float

	@Required
	@Column("BigInt")
	volumeAsset0: BigInt

	@Required
	@Column("BigInt")
	volumeAsset1: BigInt

	@Required
	@Column("Float")
	volumeAsset0Decimal: Float

	@Required
	@Column("Float")
	volumeAsset1Decimal: Float
  constructor(data: PoolSnapshotConstructorInput) {super()}

  pool(): Promise<Pool> {
    return this._pool
  }

  setPool(pool: Pool) {
    if (pool) this.poolID = pool.id
  }
}


const source = `type Pool @entity {
  id: ID!
  asset0: String!
  asset1: String!
  isStable: Boolean!
  lpToken: String!

  lpTokenSupply: BigInt!
  lpTokenSupplyDecimal: Float!

  reserve0: BigInt!
  reserve1: BigInt!
  reserve0Decimal: Float!
  reserve1Decimal: Float!

  volumeAsset0: BigInt!
  volumeAsset1: BigInt!
  volumeAsset0Decimal: Float!
  volumeAsset1Decimal: Float!

  mostRecentSnapshot: Int!
}

type PoolSnapshot @entity {
  id: ID!
  pool: Pool!
  timestamp: Int!
  lpTokenSupply: BigInt!
  lpTokenSupplyDecimal: Float!

  transactions: Int!

  reserve0: BigInt!
  reserve1: BigInt!
  reserve0Decimal: Float!
  reserve1Decimal: Float!

  volumeAsset0: BigInt!
  volumeAsset1: BigInt!
  volumeAsset0Decimal: Float!
  volumeAsset1Decimal: Float!
}
`
DatabaseSchema.register({
  source,
  entities: {
    "Pool": Pool,
	"PoolSnapshot": PoolSnapshot
  }
})
